import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { ApiError } from "../../../lib/http/api-error";
import { getOperationalImportCatalog, uploadOperationalImport } from "../api/operational-imports";
import type { ImportCatalog, ImportResult } from "../api/operational-imports";

export function OperationalImportsPage() {
  const [parameters] = useSearchParams();
  const [catalog, setCatalog] = useState<ImportCatalog | null>(null);
  const [type, setType] = useState(parameters.get("type") ?? "workforce_schedule");
  const [month, setMonth] = useState(parameters.get("competence_month") ?? "2026-08");
  const [file, setFile] = useState<File | null>(null);
  const [result, setResult] = useState<ImportResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { const controller = new AbortController(); void getOperationalImportCatalog(controller.signal).then(setCatalog).catch((cause: unknown) => setError(cause instanceof ApiError ? cause.message : "Não foi possível consultar as importações.")); return () => controller.abort(); }, []);
  const selected = useMemo(() => catalog?.items.find((item) => item.type === type), [catalog, type]);
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!file || !selected || selected.status !== "ready") return; setLoading(true); setError(null); setResult(null); try { setResult(await uploadOperationalImport(type, file, selected.requires_competence ? month : undefined)); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Não foi possível realizar a importação."); } finally { setLoading(false); } }
  return <div className="page-stack"><header className="page-header"><div><p className="eyebrow">Entrada operacional</p><h1>Importações</h1><p>Envie as exportações originais; interpretação e persistência acontecem no backend.</p></div></header><form className="schedule-filters import-form" onSubmit={submit}><label>Tipo<select value={type} onChange={(event) => { setType(event.target.value); setFile(null); setResult(null); }}>{catalog?.items.map((item) => <option key={item.type} value={item.type}>{item.label}{item.status === "not_ready" ? " — indisponível" : ""}</option>)}</select></label>{selected?.requires_competence && <label>Competência<input type="month" value={month} onChange={(event) => setMonth(event.target.value)} required /></label>}<label>Arquivo<input aria-label="Arquivo operacional" type="file" accept={selected?.accepted_extensions.join(",")} onChange={(event) => setFile(event.target.files?.[0] ?? null)} /></label><button type="submit" disabled={loading || !file || selected?.status !== "ready"}>{loading ? "Importando..." : "Importar"}</button></form>{selected?.status === "not_ready" && <div className="schedule-error" role="status">Importação ainda não disponível: {selected.not_ready_reason}</div>}{error && <div className="schedule-error" role="alert">{error}</div>}{result && <section className="import-result"><h2>{result.status === "success" ? "Importação concluída" : "Importação concluída com inconsistências"}</h2><p>{result.filename}</p><div className="delay-summary"><div>Registros<strong>{result.total_records}</strong></div><div>Novos<strong>{result.accepted_records}</strong></div><div>Duplicados<strong>{result.duplicate_records}</strong></div><div>Rejeitados<strong>{result.rejected_records}</strong></div><div>Conflitos<strong>{result.conflict_records}</strong></div></div>{result.coverages.map((coverage) => <p key={coverage.dataset}>Cobertura: <strong>{coverage.dataset}</strong> até {coverage.covered_through}</p>)}{result.issues.length > 0 && <ul className="issue-list">{result.issues.map((issue, index) => <li key={`${issue.code}-${issue.row ?? index}`}><div><strong>{issue.message}</strong><p>{issue.row ? `Linha ${issue.row}` : "Arquivo"}{issue.external_identity ? ` · ${issue.external_identity}` : ""}</p>{issue.raw_value && <small>Valor: {issue.raw_value}</small>}</div></li>)}</ul>}</section>}<section className="issues-center"><h2>Importações recentes</h2><p>{catalog?.history_available ? "Consulte as execuções registradas." : "Histórico detalhado ainda não está disponível para estes importadores operacionais."}</p></section></div>;
}
