"""Casos de uso e portas da camada Application."""

from supervisor_ai.application.csat import CsatFilters
from supervisor_ai.application.errors import (
    ApplicationConflict,
    AttendanceFactConflict,
    CollaboratorExternalIdentityConflict,
    CollaboratorExternalIdentityNotFound,
    CommercialEventConflict,
    CommercialEventNotFound,
    CsatEvaluationConflict,
    LedgerConflict,
    OperationalCollaboratorProfileConflict,
    OperationalCollaboratorProfileNotFound,
    ProcessingRunNotFound,
)
from supervisor_ai.application.financial_snapshot import (
    FinancialSnapshot,
    PaymentFacts,
    RemunerationFacts,
    RemunerationPostingFacts,
)
from supervisor_ai.application.persistence import (
    AttendanceFact,
    CollaboratorExternalIdentity,
    CollaboratorFinancialTimelineCursorPosition,
    CollaboratorFinancialTimelineRecord,
    CommercialEvent,
    CommercialEventCursorPosition,
    CsatEvaluation,
    CsatSummaryGroupRecord,
    CsatSummaryRecord,
    OperationalCollaboratorProfile,
    ProcessingHealthCount,
    ProcessingHealthRecord,
    ProcessingRun,
    ProcessingRunCursorPosition,
    ProcessingRunListRecord,
)
from supervisor_ai.application.ports import (
    AttendanceRepository,
    Clock,
    CollaboratorExternalIdentityRepository,
    CsatRepository,
    EventRepository,
    LedgerRepository,
    OperationalCollaboratorProfileRepository,
    ProcessingRunIdGenerator,
    ProcessingRunRepository,
    UnitOfWork,
    UnitOfWorkFactory,
)
from supervisor_ai.application.recurrence import (
    AttendanceFilters,
    RecurrenceCohortQuery,
)

__all__ = [
    "AttendanceFact",
    "AttendanceFactConflict",
    "AttendanceFilters",
    "AttendanceRepository",
    "ApplicationConflict",
    "CollaboratorExternalIdentity",
    "CollaboratorExternalIdentityConflict",
    "CollaboratorExternalIdentityNotFound",
    "CollaboratorExternalIdentityRepository",
    "CommercialEvent",
    "CommercialEventConflict",
    "CommercialEventCursorPosition",
    "CollaboratorFinancialTimelineCursorPosition",
    "CollaboratorFinancialTimelineRecord",
    "CommercialEventNotFound",
    "CsatEvaluation",
    "CsatEvaluationConflict",
    "CsatFilters",
    "CsatRepository",
    "CsatSummaryGroupRecord",
    "CsatSummaryRecord",
    "Clock",
    "EventRepository",
    "FinancialSnapshot",
    "LedgerRepository",
    "LedgerConflict",
    "OperationalCollaboratorProfile",
    "OperationalCollaboratorProfileConflict",
    "OperationalCollaboratorProfileNotFound",
    "OperationalCollaboratorProfileRepository",
    "PaymentFacts",
    "ProcessingRun",
    "ProcessingHealthCount",
    "ProcessingHealthRecord",
    "ProcessingRunCursorPosition",
    "ProcessingRunListRecord",
    "ProcessingRunNotFound",
    "ProcessingRunIdGenerator",
    "ProcessingRunRepository",
    "RemunerationFacts",
    "RemunerationPostingFacts",
    "RecurrenceCohortQuery",
    "UnitOfWork",
    "UnitOfWorkFactory",
]
